---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-mlx-1
spec:
  resourceName: nicmlx1
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  isRdma: true
  numVfs: 4
  nicSelector:
    vendor: "15b3"
    pfNames: ['ens787f0']
    rootDevices: ['0000:88:00.0']

---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-mlx-2
spec:
  resourceName: nicmlx2
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  priority: 99
  isRdma: true
  numVfs: 4
  nicSelector:
    vendor: "15b3"
    pfNames: ['ens787f1']
    rootDevices: ['0000:88:00.1']
